### ISSUE TITLE
Improve Automation

### ISSUE THREAD

**Issue by chrisreddington** [chrisreddington/rss-parser#12]
# Task List

## Push/PRs
- [x] Check dist is most up to date prior to merge into main
- [x] Check that a local RSS file parses correctly
- [x] Add dependency-review action for checking bad dependency merges

## Publishing (aka Push with tags)
- [x] Create a release on a new tag pushed to production

**Comment by chrisreddington** [comment]
Closing this issue, as 'initial iteration' is complete. More advanced scenarios could follow later in separate issues.
